# Sandpiper cross-platform build/test/deploy file (using https://taskfile.dev)

# Copyright The Sandpiper Authors. All rights reserved.
# Use of this source code is governed by The Artistic License 2.0
# as found in the LICENSE file.

version: '2'

vars:
  REPO:
    github.com/sandpiper-framework/sandpiper

tasks:
  create-db:
    desc: Create the database(s) from default postgresql installation using "psql" (*obsoleted* by `sandpiper init`)
    dir: pkg/api/migrations
    cmds:
      - "{{.PSQLCMD}}"
    vars:
      PSQLCMD:
        '{{if eq OS "linux"}}sudo -u postgres {{end}}psql --username=postgres --file=db_create.sql --quiet'

  init:
    desc: Create the PostgreSQL database and initialize it
    dir: cmd/cli
    cmds:
      - ./sandpiper init

  update:
    desc: Get the latest Sandpiper server repo
    cmds:
      - go get -u {{.REPO}}

  rice:
    desc: Add rice dependency and install if necessary
    cmds:
      - go get github.com/GeertJohan/go.rice/rice
    silent: true

  rice-api:
    desc: Use rice to encode static http files in a go source file
    dir: pkg/api
    deps: [rice]
    cmds:
      - rice embed-go
    sources:
      - api.go
    generates:
      - rice-box.go

  build-api:
    desc: Build sandpiper primary server
    dir: cmd/api
    deps: [rice-api]
    cmds:
      - go build -v -o {{.EXE}} -ldflags="-X github.com/sandpiper-framework/sandpiper/pkg/api/version.Version={{.VER}}"
    vars:
      EXE: api{{exeExt}}
      VER: {sh: git describe --always --long --dirty}

  build-cli:
    desc: Build sandpiper cli command
    dir: cmd/cli
    cmds:
      - go build -v -o {{.EXE}} -ldflags="-X github.com/sandpiper-framework/sandpiper/pkg/cli/version.Version={{.VER}}"
    vars:
      EXE: sandpiper{{exeExt}}
      VER: {sh: git describe --always --long --dirty}

  build:
    desc: Build all sandpiper executables
    deps: [build-api, build-cli]

  test:
    desc: Run test suite (having trouble with dockertesting under Windows!)
    cmds:
      - echo " *** Running Coverage Tests ***"
      - go test -v -race -coverprofile=profile.out -covermode=atomic ./...
      - sh: cat profile.out >> coverage.txt
      - sh: docker stop $(docker ps -a -q)
      - echo " *** Completed *** "
    vars:
      # couldn't get "preconditions" to work, but this will fail if docker is not running
      DOCKER_RUNNING: {sh: docker ps -q}
    silent: true

  server:
    desc: Launch sandpiper primary (publication) server
    dir: cmd/api
    cmds:
      - ./api

  primary:
    desc: Launch sandpiper primary (publication) server
    dir: cmd/api
    cmds:
      - ./api -config api-primary.yaml

  secondary:
    desc: Launch sandpiper secondary (subscribing) server
    dir: cmd/api
    cmds:
      - ./api -config api-secondary.yaml

  sync:
    desc: Initiate a sync process against our secondary server
    dir: cmd/cli
    cmds:
      - ./sandpiper -config cli-secondary.yaml sync

  release-docker:
    desc: Create a docker file for release
    deps: [build]
    cmds:
      - docker build . -t sandpiper
    preconditions:
      - test -f Dockerfile

  clean-docker:
    desc: Remove any unused docker images (FIX THIS!!!)
    cmds:
      # docker ps -a -q -f status=exited | xargs docker rm
      # docker images --no-trunc=true --filter dangling=true --quiet | xargs docker rmi
      - sh: docker stop $(docker ps -a -q)
      - sh: docker rm $(docker ps -a -q)
      - sh: docker volume rm $(docker volume ls -qf dangling=true)
