version: '2'

tasks:
  print-os:
    cmds:
      - echo '{{OS}} {{ARCH}}'
      - echo '{{if eq OS "windows"}}windows-command{{else}}unix-command{{end}}'
      # This will be path/to/file on Unix but path\to\file on Windows
      - echo '{{fromSlash "path/to/file"}}'
  test:
    cmds:
      - echo " *** Running Coverage Tests ***"
      - $(pwd)/test.sh
      - echo " *** Completed *** "
    silent: true
  build:
    desc: Build sandpiper
    dir: cmd/api
    cmds:
      - go build -v -o {{.EXE}} -ldflags="-X main.version={{.VER}}"
    vars:
      EXE: sandpiper{{exeExt}}
      VER: {sh: git describe --always --long --dirty}