# Sandpiper cross-platform build/test file (using https:\\taskfile.dev)

# Copyright Auto Care Association. All rights reserved.
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE.md file.

version: '2'

vars:
  REPO:
    github.com/dougwinsby/sp-srv
  GO_PACKAGES:
    sh: go list ./...

tasks:
  createdb:
    desc: Create the sandpiper database after default postgresql installation
    dir: cmd/migration/migrations
    cmds:
      - "{{.PSQLCMD}}"
    vars:
      PSQLCMD:
        '{{if eq OS "linux"}}sudo -u postgres {{end}}psql --username=postgres --file=db_create.sql'

  update:
    desc: Get the latest Sandpiper server repo
    cmds:
      - go get -u {{.REPO}}

  packages:
    cmds:
      - echo '{{.GO_PACKAGES}}'
    silent: true

  build:
    desc: Build sandpiper
    dir: cmd/api
    cmds:
      - go build -v -o {{.EXE}} -ldflags="-X autocare.org/sandpiper/pkg/version.Version={{.VER}}"
    vars:
      EXE: api{{exeExt}}
      VER: {sh: git describe --always --long --dirty}

  test:
    desc: Run test suite (currently doesn't work with tests using dockertest under windows!)
    cmds:
      - echo " *** Running Coverage Tests ***"
      - go test -v -race -coverprofile=profile.out -covermode=atomic ./...
      - sh: cat profile.out >> coverage.txt
      - sh: docker stop $(docker ps -a -q)
      - echo " *** Completed *** "
    vars:
      # couldn't get "preconditions" to work, but this will fail if docker is not running
      DOCKER_RUNNING: {sh: docker ps -q}
    silent: true

  run:
    desc: Launch sandpiper server
    dir: cmd/api
    cmds:
      - ./api

  release-docker:
    desc: Create a docker file for release
    deps: [build]
    cmds:
      - docker build . -t sandpiper
    preconditions:
      - test -f Dockerfile

  clean-docker:
    desc: Remove any unused docker images (FIX THIS!!!)
    cmds:
      - docker ps -a -q -f status=exited | xargs docker rm
      - docker images --no-trunc=true --filter dangling=true --quiet | xargs docker rmi
