# Copyright The Sandpiper Authors. All rights reserved.
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE.md file.

# sandpiper server configuration file

database:
  dialect: postgres
  network: tcp           # "tcp" or "unix" (for unix domain sockets) ("DB_NETWORK")
  host: localhost        # localhost, ip addr or unix socket (/var/run/postgresql) ("DB_HOST")
  port: 5432             # port number  ("DB_PORT")
  database: sandpiper    # database name ("DB_DATABASE")
  user: sandpiper        # database role ("DB_USER")
  password: development  # plaintext password ("DB_PASSWORD")
  sslmode: disable       # "disable", "allow", "verify-ca" ("DB_SSLMODE")
  timeout_seconds: 5
  log_queries: true

server:
  port: 8080
  read_timeout_seconds: 10
  write_timeout_seconds: 5
  max_sync_procs: 5
  debug: false   # WARNING: debug creates non-JSON responses (but shows underlying errors). Not for production!
  # ** Change this sample secret!!! (required only on "primary" server) **
  # Can override with "APIKEY_SECRET" env variable
  # This should be a Base64 Encoded AES-256 key (44 chars)
  # generate with `sandpiper secrets`
  api_key_secret: u7WJ3kpqyvAkKb7HIfYJoSok2DoqTa9YhaCUhUujqb8=

jwt:
  # ** Change this sample secret!!! (required on all servers) **
  # Can override secret with "JWT_SECRET" env variable
  # generate with `sandpiper secrets`
  secret: WuBF5X3FS8IYGb5BblKPJxfrDHAHJYWqG649C+qAafmXy0fow0IX8NpDPQXuHRuUbLSlX/L0IjdD5Lu2dWQOMw
  duration_minutes: 15
  refresh_duration_minutes: 15
  max_refresh_minutes: 1440
  signing_algorithm: HS256
  min_secret_length: 64

application:
  min_password_strength: 1  # 0,1,2,3,4
  service_logging: true
