# sandpiper server configuration file

database:
  log_queries: true
  timeout_seconds: 5
  dialect: postgres
  database: sandpiper
  user: sandpiper       # Can override with "DB_USER" env variable
  password: autocare    # Use "DB_PASSWORD" env variable in production!!!
  host: localhost
  port: 5432
  sslmode: disable

server:
  port: :8080
  debug: true
  read_timeout_seconds: 10
  write_timeout_seconds: 5

jwt:
  secret: jwtrealm # Change this value
  duration_minutes: 15
  refresh_duration_minutes: 15
  max_refresh_minutes: 1440
  signing_algorithm: HS256

application:
  min_password_strength: 1  # 0,1,2,3,4
  service_logging: true
