# Copyright The Sandpiper Authors. All rights reserved.
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE.md file.

# sandpiper secondary configuration file

database:
  log_queries: true
  timeout_seconds: 5
  dialect: postgres
  database: sandpiper
  user: sandpiper       # Can override with "DB_USER" env variable
  password: autocare    # Use "DB_PASSWORD" env variable in production!!!
  host: localhost
  port: 5432
  sslmode: disable

server:
  port: :4040
  debug: true
  read_timeout_seconds: 10
  write_timeout_seconds: 5

jwt:
  # ** Change this sample secret!!! **
  # Can override secret with "JWT_SECRET" env variable
  # One way to generate a random "secret" (if you have nodejs installed) is with this command:
  # node -e "console.log(require('crypto').randomBytes(64).toString('base64'));"
  secret: WuBF5X3FS8IYGb5BblKPJxfrDHAHJYWqG649C+qAafmXy0fow0IX8NpDPQXuHRuUbLSlX/L0IjdD5Lu2dWQOMw
  duration_minutes: 15
  refresh_duration_minutes: 15
  max_refresh_minutes: 1440
  signing_algorithm: HS256
  min_secret_length: 64

application:
  min_password_strength: 1  # 0,1,2,3,4