// Copyright The Sandpiper Authors. All rights reserved.
// This file is licensed under the Artistic License 2.0.
// License text can be found in the project's LICENSE file.

# `sandpiper` command configuration file
# commands look for a "config.yml" in the current directory

command:
  url: http://localhost
  port: 8080
  max_sync_procs: 5
