// Copyright The Sandpiper Authors. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE.md file.

# `sandpiper` command configuration file
# commands look for a "config.yml" in the current directory

command:
  url: http://localhost
  port: 8080
  max_sync_procs: 5
