# `sandpiper` command configuration file
# commands look for a "config.yml" in the current directory

command:
  url: http://localhost
  port: 8080
  retry_count: 3
  retry_delay: 5  # seconds
  sync_pool: 5
